apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd
  labels:
    app: alpha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpha
  template:
    metadata:
      labels:
        app: alpha
    spec:
      containers:
        - name: cont1
          image: 445567098528.dkr.ecr.ap-south-1.amazonaws.com/ci-cd:5-2e9c997
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: ENV
              value: "dev"
